### ISSUE TITLE
Add more example for better understanding

### ISSUE THREAD

**Issue by AB-san** [derekprior/add-autoresponse#3]
I tried to add autoresponse when someone else's pull request is merged into my repo
but it works fine for me only ,i.e. sends a auto message when I merge my own pull request

shows the following check fails ->

![image](https://user-images.githubusercontent.com/71064674/114505276-c2d3b000-9c4d-11eb-996c-5c5db3adc0be.png)

**Comment by AB-san** [comment]
I can fix this issue please assign me

**Comment by AB-san** [comment]
i just now realised that theres no bug in code , but the example in the  documentation requires slight changes , besides I can also give an another example under the usage , which will help the other users.

If these sounds good to you , let me know , so that i can start working on it right away.

**Comment by derekprior** [comment]
Sounds good!

**Comment by AB-san** [comment]
> Sounds good!

Okay :)
